server:
  servlet:
    context-path: /
  port:
    8765
spring:
  profiles:
    active:
      - ${ACTIVE_SPRING_PROFILE:dev}
  application:
    name: api-gateway
springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway Service
      - url: /amazon-services/v3/api-docs
        name: amazon-services
      - url: /create-recipe/v3/api-docs
        name: create-recipe
      - url: /credentials/v3/api-docs
        name: credentials
      - url: /email-sender/v3/api-docs
        name: email-sender
      - url: /profile-api/v3/api-docs
        name: profile-api
      - url: /profile-picture-downloader/v3/api-docs
        name: profile-picture-downloader
      - url: /search-profile/v3/api-docs
        name: search-profile  
